CORE-1066: Handle "verified_block_hash" in Swift/Java as optional
blockset-corp/walletkit pull request #171
Opened 2020-11-10 18:15 UTC by ewerx

2020-11-10 20:43 UTC, EBGToo requested changes

2020-11-10 20:43 UTC, EBGToo commented on WalletKitCore/src/crypto/BRCryptoNetwork.c
> +    : NULL;
All the 'take' functions now accept a `NULL` argument and simply return it.

2020-11-10 20:43 UTC, EBGToo commented on WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Blockchain.java
> +                                    @JsonProperty("verified_block_hash") Optional<String> verifiedBlockHash) {
Does an `Optional` actually get passed here?  Other classes, see `Block`, annotate the argument as `@Nullable`, save the field as `null` and then the corresponding getter uses `Optional.fromNullable` (see `Block.getRaw()`).  I'd prefer consistency with the existing approach.

2020-11-10 21:36 UTC, ewerx commented on WalletKitCore/src/crypto/BRCryptoNetwork.c
> +    : NULL;
On refactor branch only?

2020-11-10 21:37 UTC, ewerx commented on WalletKitJava/crypto/src/main/java/com/breadwallet/crypto/blockchaindb/models/bdb/Blockchain.java
> +                                    @JsonProperty("verified_block_hash") Optional<String> verifiedBlockHash) {
Fixed

2020-11-10 22:44 UTC, EBGToo commented on WalletKitCore/src/crypto/BRCryptoNetwork.c
> +    : NULL;
Sorry, right.

2020-11-11 00:12 UTC, EBGToo approved these changes

2020-11-11 19:15 UTC, merged