Feature/core 1178: stellar-core
blockset-corp/walletkit pull request #278
Opened 2021-05-27 22:07 UTC by carlcherry

Initial checkin for Stellar support. Will need data in Blockset next to test properly.

2021-05-28 18:09 UTC, EBGToo requested changes

2021-05-28 18:09 UTC, EBGToo commented on WalletKitCore/src/stellar/utils/crc16.h
> +#include <stdlib.h>
Change from `#ifndef` idiom?

2021-05-28 18:09 UTC, EBGToo commented on WalletKitCore/src/walletkit/WKAccount.c
> +#define ACCOUNT_SERIALIZE_DEFAULT_VERSION  5
Going to be conflicts w/ LTC and DOGE...

2021-06-02 17:40 UTC, EBGToo commented on WalletKitCore/src/walletkit/WKAccount.c
> +#define ACCOUNT_SERIALIZE_DEFAULT_VERSION  5
[I resolved this with the 'develop' merge.]

2021-06-02 19:04 UTC, carlcherry commented on WalletKitCore/src/stellar/BRStellarAccountUtils.c
> +}
Not sure - it was so long ago. When I create new chains I attempt to find some reference code and create an address with a paper key I can control. Then try to reproduce that in WalletKit so we have some idea that it will be compatible.

2021-06-02 19:05 UTC, carlcherry commented on WalletKitCore/src/stellar/BRStellarDecode.c
> +    buffer = unpack_uint64(buffer, &offerEntry->offerID);
Decode is not being used - will most likely just get rid of it (later).

2021-06-02 20:20 UTC, EBGToo approved these changes

2021-06-02 20:26 UTC, merged