CORE-1213: Switch account support
blockset-corp/walletkit pull request #293
Opened 2021-06-23 19:12 UTC by bgoring

2021-06-23 21:53 UTC, EBGToo requested changes

2021-06-23 21:53 UTC, EBGToo commented on .cproject
> +			<storageModule buildSystemId="org.eclipse.cdt.managedbuilder.core.configurationDataProvider" id="cdt.managedbuild.config.gnu.cross.exe.debug.1358400441" moduleId="org.eclipse.cdt.core.settings" na
I don't think this should be checked in.  Is this an Android Studio file outside of .../WalletKit/WalletKitJava?  Shouldn't be.

2021-06-23 21:53 UTC, EBGToo commented on .project
> +	<buildSpec>
Ditto

2021-06-23 21:53 UTC, EBGToo commented on .settings/language.settings.xml
> +			<provider copy-of="extension" id="org.eclipse.cdt.ui.UserLanguageSettingsProvider"/>
Ditto

2021-06-23 21:53 UTC, EBGToo commented on WalletKitJava/WalletKitDemo-Android/src/main/java/com/blockset/walletkit/demo/DemoApplication.java
> +            Date     timestamp       ) {
Why not pass the account instance here?  From `...utility.AccountSpecification`

2021-06-23 21:53 UTC, EBGToo commented on WalletKitJava/WalletKitDemo-Android/src/main/java/com/blockset/walletkit/demo/WalletListActivity.java
> +
This 'default' is the initial account?  FYI - The Swift code finds the account from a 'arguments pass on launch'.  Might allow the User to select - as we've discussed.

2021-06-23 21:53 UTC, EBGToo commented on WalletKitJava/WalletKitDemo-Android/src/main/res/values/strings.xml
>  </resources>
Is `Wallets` used for `Switch Account`?  Is `"wallets_list_title"` used for `"account_list_title"`?

2021-06-23 21:53 UTC, EBGToo commented on WalletKitJava/WalletKitDemo-Android/src/main/java/com/blockset/walletkit/demo/DemoApplication.java
> +            System.wipe(system);
Okay!

2021-06-24 10:42 UTC, bgoring commented on .settings/language.settings.xml
> +			<provider copy-of="extension" id="org.eclipse.cdt.ui.UserLanguageSettingsProvider"/>
Ok, chalk this up to using a new git tool. These files are eclipse project files, I'll remove them.

2021-06-24 13:50 UTC, bgoring commented on WalletKitJava/WalletKitDemo-Android/src/main/java/com/blockset/walletkit/demo/DemoApplication.java
> +            Date     timestamp       ) {
A good idea. I moved to specifying the AccountSpecification in its entirety and also serializing the chosen AccountSpecification in the Intent when launching the Demo Application (rather than serializing all its individual fields in separate intent fields).

2021-06-24 13:53 UTC, bgoring commented on WalletKitJava/WalletKitDemo-Android/src/main/java/com/blockset/walletkit/demo/WalletListActivity.java
> +
In the context of the WalletKitActivity this sets initial account setting fields in the Intent with which DemoApplication is initialized. We set the blockset URL and Token in the Intent, these things do not change, but the details of the account do as the user switches it. I have moved account switching to passing the account spec details of chosen account, including the initial selection as described by the loaded JSON to an object as noted above.

I did some investigation, I found there is a way to launch android activity from the command line with arguments that can specify an intent Extra field. So this could be done if its deemed useful. Alternately, the user launches the app in Android Studio, the initial account is the one presented first in the WalletKitTestsConfig.json, and the user can switch using the "Switch Account" dialog.

2021-06-24 13:54 UTC, bgoring commented on WalletKitJava/WalletKitDemo-Android/src/main/java/com/blockset/walletkit/demo/DemoApplication.java
> +            System.wipe(system);
Worked like a charm...

2021-06-24 13:55 UTC, bgoring commented on .cproject
> +			<storageModule buildSystemId="org.eclipse.cdt.managedbuilder.core.configurationDataProvider" id="cdt.managedbuild.config.gnu.cross.exe.debug.1358400441" moduleId="org.eclipse.cdt.core.settings" na
Removed.

2021-06-24 13:55 UTC, bgoring commented on .project
> +	<buildSpec>
Removed.

2021-06-24 13:55 UTC, bgoring commented on .settings/language.settings.xml
> +			<provider copy-of="extension" id="org.eclipse.cdt.ui.UserLanguageSettingsProvider"/>
Removed

2021-06-24 14:09 UTC, bgoring commented on WalletKitJava/WalletKitDemo-Android/src/main/res/values/strings.xml
>  </resources>
"Wallets" string is combined with account identifier and testnet/mainnet title in the wallet list activity. This is to have the similar presentation of wallets as what I saw in swift. There is a case we may make all such strings internationalized, there may be other hardcoded strings elsewhere.

2021-06-24 14:25 UTC, EBGToo approved these changes

2021-06-24 14:30 UTC, merged