Feature/core 1199
blockset-corp/walletkit pull request #321
Opened 2021-08-04 19:21 UTC by AmitBRD

Add generated avax files

2021-08-05 14:26 UTC, EBGToo submitted a review, later dismissed

2021-08-05 16:44 UTC, bgoring commented on WalletKitJava/WalletKit/src/main/java/com/blockset/walletkit/NetworkType.java
> +    AVAX,n    /* __SYMBOL__ */
this and below still have the newline issue, wont compile...

2021-08-05 16:44 UTC, bgoring approved these changes

2021-08-05 16:52 UTC, EBGToo commented on WalletKitJava/WalletKit/src/main/java/com/blockset/walletkit/NetworkType.java
> +    AVAX,n    /* __SYMBOL__ */
@AmitBRD please have a look and update!

2021-08-05 22:58 UTC, EBGToo requested changes
I'm confused; was something reverted?  I thought there were only two errors; but the errors are all over.  Is it compiling?

2021-08-05 22:58 UTC, EBGToo commented on WalletKitCore/WalletKitCoreTests/WalletKitCoreTests.swift
> +        // Avalanchen        ("testAvalanche", testAvalanche),n        // __NEW_BLOCKCHAIN_TEST__
Still a problem?

2021-08-05 22:58 UTC, EBGToo commented on WalletKitCore/include/WKBase.h
> +    WK_NETWORK_TYPE_AVAX,n    /* WK_NETWORK_TYPE___SYMBOL__ */
Still a problem?

2021-08-05 22:58 UTC, EBGToo commented on WalletKitCore/include/WKBase.h
> +#define WK_NETWORK_CURRENCY_AVAX    "avax" n/* #define WK_NETWORK_CURRENCY___SYMBOL__    "__symbol__" */
Still here?

2021-08-05 22:58 UTC, EBGToo commented on WalletKitCore/src/walletkit/WKConfig.h
> +// MARK: AVAX Mainnetnn#define NETWORK_NAME    "Avalanche"nDEFINE_NETWORK (WK_NETWORK_TYPE_AVAX,  "avalanche-mainnet", NETWORK_NAME, "mainnet", true, 35516170, 1, 5)nDEFINE_NETWORK_FEE_ESTIMATE ("ava
This too?  @bgoring what is happening here?

2021-08-05 22:58 UTC, EBGToo commented on WalletKitJava/WalletKitBRD/src/main/java/com/blockset/walletkit/brd/Utilities.java
> +            case AVAX: return WKNetworkType.AVAX; n            /* case __SYMBOL__: return WKNetworkType.__SYMBOL__; */
Here?

2021-08-06 15:09 UTC, EBGToo commented on WalletKitCore/CMakeLists.txt
> +# Avalanche Testsnif (CMAKE_BUILD_TYPE MATCHES Debug)n    target_sources (WalletKitCoreTestn            PRIVATEn            ${PROJECT_SOURCE_DIR}/WalletKitCoreTests/test/avax/testAvalanche.cn)nendif(
Aren't all of these wrong?  @bgoring ?

2021-08-06 15:10 UTC, bgoring commented on WalletKitCore/CMakeLists.txt
> +# Avalanche Testsnif (CMAKE_BUILD_TYPE MATCHES Debug)n    target_sources (WalletKitCoreTestn            PRIVATEn            ${PROJECT_SOURCE_DIR}/WalletKitCoreTests/test/avax/testAvalanche.cn)nendif(
Yes it looks again that the newline is being processed incorrectly.

2021-08-06 15:48 UTC, EBGToo approved these changes

2021-08-06 19:11 UTC, merged