CORE-1276: Add public key recovery from digest + signature
blockset-corp/walletkit pull request #363
Opened 2021-09-14 20:27 UTC by bgoring

2021-09-14 21:25 UTC, EBGToo requested changes

2021-09-14 21:25 UTC, EBGToo commented on WalletKitCore/src/walletkit/handlers/eth/WKWalletConnectorETH.c
> +    }
Should be `signatureLength`

2021-09-14 21:25 UTC, EBGToo commented on WalletKitSwift/WalletKit/WKWalletManager.swift
> +            let digestLength = digestBytes.count
This doesn't compile?

It doesn't follow the `withUnsafeBytes` pattern.  Should be, maybe:
```
return digest.data32.withUnsafeBytes ...
```

2021-09-14 21:25 UTC, EBGToo commented on WalletKitSwift/WalletKit/WKWalletManager.swift
> +                let signatureLength = signatureBytes.length
Doesn't compile?

2021-09-14 21:25 UTC, EBGToo commented on WalletKitSwift/WalletKit/WKWalletManager.swift
> +                let signatureLength = signatureBytes.length
And `length` is not a property/function in Swift.  Should be `signatureBytes.count`.

2021-09-14 21:25 UTC, EBGToo commented on WalletKitSwift/WalletKit/WKWalletManager.swift
> +                return Result.success(Key(core: key));
`key` is `uint8_t*` but `Key(core: key)` expects `BRKey`?

2021-09-14 21:25 UTC, EBGToo commented on WalletKitCore/include/WKWalletConnector.h
> +
There is no implementation of this function?

2021-09-15 11:22 UTC, bgoring commented on WalletKitCore/src/walletkit/handlers/eth/WKWalletConnectorETH.c
> +    }
fixed

2021-09-15 11:31 UTC, bgoring commented on WalletKitCore/include/WKWalletConnector.h
> +
It not likely to work without that! Added.

2021-09-15 11:37 UTC, bgoring commented on WalletKitSwift/WalletKit/WKWalletManager.swift
> +            let digestLength = digestBytes.count
Missed these compile problems w/o WalletKitDemo scheme enabled. Fixed

2021-09-15 11:38 UTC, bgoring commented on WalletKitSwift/WalletKit/WKWalletManager.swift
> +                let signatureLength = signatureBytes.length
Fixed

2021-09-15 11:51 UTC, bgoring commented on WalletKitSwift/WalletKit/WKWalletManager.swift
> +                return Result.success(Key(core: key));
Hold on. I have the interface wrong. It should return a WKKey. Fixed

2021-09-15 15:06 UTC, EBGToo approved these changes

2021-09-15 15:43 UTC, merged